export const programs = [
  // ================= DIPLOMA =================
  {
    programLevel: "Diploma",
    name: "Diploma in Computer Engineering (AI Tools)",
    campus: "Narela",
    eligibility:
      "Passed Class X (CBSE or equivalent) with minimum 40% OR 2-year NTC after 8th with 40% OR 40 credits at NCrF level 3.0",
    about: "Diploma",
    fees: "₹10,000/-",
    duration: "3 Year – Technical Diploma",
    link: "",
  },

  // ============ CERTIFICATE PROGRAMS ============
  {
    programLevel: "Certificate Programs",
    name: "Certificate course in Refrigeration and Air Conditioning Skills (HVAC)",
    campus: "Aryabhatt",
    eligibility:
      "XII Pass OR 10th + 2-Year NTC/NAC/CITS OR 40 credits of NSQF level 4.0 or equivalent",
    about: "Certificate Programs",
    fees: "₹25,000/-",
    duration: "1 Year (After 12th)",
    link: "",
  },
  {
    programLevel: "Certificate Programs",
    name: "UG Certificate AI in Office Operations",
    campus: "Narela",
    eligibility:
      "XII Pass OR 10th + 2-Year NTC/NAC/CITS OR 40 credits of NSQF level 4.0 or equivalent",
    about: "Certificate Programs",
    fees: "₹25,000/-",
    duration: "1 Year (After 12th)",
    link: "",
  },
  {
    programLevel: "Certificate Programs",
    name: "UG Certificate in Installation, Testing, Maintenance and Repair of Solar Panels",
    campus: "Dwarka",
    eligibility:
      "XII Pass OR 10th + 2-Year NTC/NAC/CITS OR 40 credits of NSQF level 4.0 or equivalent",
    about: "Certificate Programs",
    fees: "₹25,000/-",
    duration: "1 Year (After 12th)",
    link: "",
  },
  {
    programLevel: "Certificate Programs",
    name: "UG Certificate Course in Food Production",
    campus: "Jhandewalan",
    eligibility:
      "XII Pass OR 10th + 2-Year NTC/NAC/CITS OR 40 credits of NSQF level 4.0 or equivalent",
    about: "Certificate Programs",
    fees: "₹25,000/-",
    duration: "1 Year (After 12th)",
    link: "",
  },
  {
    programLevel: "Certificate Programs",
    name: "UG Certificate course in Welding Technology",
    campus: "Wazirpur",
    eligibility:
      "XII Pass OR 10th + 2-Year NTC/NAC/CITS OR 40 credits of NSQF level 4.0 or equivalent",
    about: "Certificate Programs",
    fees: "₹10,000/-",
    duration: "1 Year (After 12th)",
    link: "",
  },

  // ========== LANGUAGE / SHORT CERTIFICATES ==========
  {
    programLevel: "Certificate Programs",
    name: "Certificate course in German",
    campus: "Pusa-II",
    eligibility: "",
    about: "Certificate Programs",
    fees: "₹15,000/-",
    duration: "",
    link: "",
  },
  {
    programLevel: "Certificate Programs",
    name: "Certificate Course in Spanish",
    campus: "Sirifort",
    eligibility: "",
    about: "Certificate Programs",
    fees: "₹15,000/-",
    duration: "",
    link: "",
  },
  {
    programLevel: "Certificate Programs",
    name: "Certificate Course in French",
    campus: "Dwarka",
    eligibility: "",
    about: "Certificate Programs",
    fees: "₹15,000/-",
    duration: "",
    link: "",
  },
  {
    programLevel: "Certificate Programs",
    name: "Certificate Program in Wheelchair Skills Training (ISIC)",
    campus: "Okhla",
    eligibility:
      "XII Pass OR 10th + 2-Year NTC/NAC/CITS OR 40 credits of NSQF level 4.0 or equivalent",
    about: "Certificate Programs",
    fees: "Approximately ₹15,000/-",
    duration: "20 Credits (After 10+2 any discipline)",
    link: "",
  },
  {
    programLevel: "Certificate Programs",
    name: "Certificate Course in Yoga and Wellness",
    campus: "Narela",
    eligibility: "",
    about: "Certificate Programs",
    fees: "",
    duration: "",
    link: "",
  },

  // ================== UG PROGRAMS ==================
  {
    programLevel: "UG Programs",
    name: "BS Optometry (in partnership with LENSKART)",
    campus: "Dheerpur",
    eligibility: "",
    about: "UG Programs",
    fees: "",
    duration: "",
    link: "",
  },
  {
    programLevel: "UG Programs",
    name: "B.S. Medical Radiology and Imaging Technology (in partnership with ISIC)",
    campus: "Dwarka",
    eligibility: "",
    about: "UG Programs",
    fees: "",
    duration: "",
    link: "",
  },

  // ================== PG DIPLOMA ==================
  {
    programLevel: "PG Diploma",
    name: "PG Diploma in AI and Intelligent Systems (Evening Batch)",
    campus: "Dwarka",
    eligibility: "Bachelor’s Degree in Science or Technology",
    about: "PG Diploma",
    fees: "₹50,000/-",
    duration: "1 Year (After Graduation)",
    link: "",
  },
  {
    programLevel: "PG Diploma",
    name: "PG Diploma in Data Analysis and Public Policy (Evening Batch)",
    campus: "Dwarka",
    eligibility: "",
    about: "PG Diploma",
    fees: "₹50,000/-",
    duration: "1 Year (After Graduation)",
    link: "",
  },
  {
    programLevel: "PG Diploma",
    name: "PG Diploma in Event Management (Evening Batch)",
    campus: "Pusa-II",
    eligibility: "",
    about: "PG Diploma",
    fees: "₹35,000/-",
    duration: "1 Year (After Graduation)",
    link: "",
  },
  {
    programLevel: "PG Diploma",
    name: "PG Diploma in Semiconductor Chip Design & Fabrication",
    campus: "Dwarka",
    eligibility: "Bachelor’s Degree in Science or Technology",
    about: "PG Diploma",
    fees: "₹50,000/-",
    duration: "1 Year (After Graduation)",
    link: "",
  },
  {
    programLevel: "PG Diploma",
    name: "PG Diploma in Dialysis Therapy Technology (ISIC)",
    campus: "Okhla",
    eligibility: "Bachelor’s Degree in Science or Technology",
    about: "PG Diploma",
    fees: "F",
    duration: "1 Year (After Graduation)",
    link: "",
  },
  {
    programLevel: "PG Diploma",
    name: "PG Diploma in Emergency Medical Technology (ISIC)",
    campus: "Okhla",
    eligibility: "Bachelor’s Degree in Science or Technology",
    about: "PG Diploma",
    fees: "F",
    duration: "1 Year (After Graduation)",
    link: "",
  },
  {
    programLevel: "PG Diploma",
    name: "PG Diploma in Emergency and OT (ISIC)",
    campus: "Okhla",
    eligibility: "BSc Nursing",
    about: "PG Diploma",
    fees: "Approximately ₹35,000/- per semester",
    duration: "1 Year (After Graduation)",
    link: "",
  },
  {
    programLevel: "PG Diploma",
    name: "PG Diploma in CTVS (ISIC)",
    campus: "Okhla",
    eligibility: "BSc Nursing",
    about: "PG Diploma",
    fees: "Approximately ₹35,000/- per semester",
    duration: "1 Year (After Graduation)",
    link: "",
  },
];
