[
    {
        "S.No.": 1,
        "Name of the File": "Pathkind Diagnostics Pvt. Ltd.",
        "MOU Signing Date": "23-Aug-2022",
        "Term/\r\nValidity": "5 years",
        "Target Program": "B.Sc/Diploma in MLT",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 2,
        "Name of the File": "Janakpuri Super Speciality Hospital ",
        "MOU Signing Date": "10-08-2022",
        "Term/\r\nValidity": "5 yrs",
        "Target Program": "Diploma in MLT and Diploma in Pharmacy",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 3,
        "Name of the File": "Forus Health",
        "MOU Signing Date": "11-08-2022",
        "Term/\r\nValidity": "2 yrs",
        "Target Program": "BA Aesthetics and Beauty Therapy",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 4,
        "Name of the File": "Hero Electric Vehicles Private Limited and WRI India",
        "MOU Signing Date": "29-08-2022",
        "Term/\r\nValidity": "3yrs",
        "Target Program": "EV Mechanic Training Program\r\nDiploma in Automobile Engineering",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 5,
        "Name of the File": "Connecting Dreams Foundation",
        "MOU Signing Date": "03-10-2022",
        "Target Program": "Community formulation for Social Change",
    },
    {
        "S.No.": 6,
        "Name of the File": "MoU between DSEU & Sales Force",
        "MOU Signing Date": 44768,
        "Term/\r\nValidity": "3 Years",
        "Target Program": "BSc Data Analytics",
    },
    {
        "S.No.": 7,
        "Name of the File": "DSIIDC",
        "MOU Signing Date": 44825,
        "Term/\r\nValidity": "5 yrs",
        "Target Program": "Engineerng and Management",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 8,
        "Name of the File": "Lotus Herbal",
        "MOU Signing Date": 44803,
        "Term/\r\nValidity": "1 yr (term Expired)- Renewal proposed",
        "Target Program": "BA Aesthtics and Beauty",
    },
    {
        "S.No.": 9,
        "Name of the File": "Enrich",
        "MOU Signing Date": 44756,
        "Term/\r\nValidity": "5 yrs",
        "Target Program": "BA Aesthetics and Beauty Therapy/ Diploma in Cosmetology",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 10,
        "Name of the File": "Manikaran Power Ltd.",
        "MOU Signing Date": 44635,
        "Term/\r\nValidity": "5 yrs",
        "Target Program": "BCA, BA (DMD), B.Com BPM, BBA FHM, BSc Data Analytics, Diploma in Architecture, Diploma in Civil Engineering, Diploma in ELectrical Engg, Diploma in Interior Design",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 11,
        "Name of the File": "LOI between DSEU & Indian Exposition Mart",
        "MOU Signing Date": "1st May 2022",
        "Term/\r\nValidity": "Letter of Intent",
        "Target Program": "BBA FHM",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 12,
        "Name of the File": "SAP",
        "MOU Signing Date": 44698,
        "Term/\r\nValidity": "2 yrs",
        "Target Program": "BSc Data Analytics",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 13,
        "Name of the File": "MoU between DSEU & NBCC",
        "MOU Signing Date": 44719,
        "Term/\r\nValidity": "5 yrs",
        "Target Program": "Diploma in Civil Engineering",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 15,
        "Name of the File": "Chetak Foundation and Chetak Logistics",
        "MOU Signing Date": 44462,
        "Term/\r\nValidity": "3yrs",
        "Target Program": "BMS (Land Transport)",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 16,
        "Name of the File": "TSSC",
        "MOU Signing Date": 44610,
        "Term/\r\nValidity": "3yrs",
        "Target Program": "Centre for excellence",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 17,
        "Name of the File": "Integreon",
        "MOU Signing Date": 44475,
        "Term/\r\nValidity": "3yrs",
        "Target Program": "BA Digital Media and Design",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 18,
        "Name of the File": "MoU between DSEU & HDFC Bank",
        "MOU Signing Date": 44466,
        "Term/\r\nValidity": "4 yrs",
        "Target Program": "BBA BFSI",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 19,
        "Name of the File": "IKIGAI LAB",
        "MOU Signing Date": 44452,
        "Term/\r\nValidity": "5 yrs",
        "Target Program": "BSc Data Analytics",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 20,
        "Name of the File": "MoU between DSEU & TCS",
        "MOU Signing Date": 44519,
        "Term/\r\nValidity": "3 yrs",
        "Target Program": "BSc Data Analytics and BA Digital Media and Design",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 21,
        "Name of the File": "MoU between DSEU & RR Donnelley",
        "MOU Signing Date": 44609,
        "Term/\r\nValidity": "3 yrs",
        "Target Program": "BA Digital Media and Design",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 22,
        "Name of the File": "Lagozon & DSEU",
        "MOU Signing Date": 44417,
        "Term/\r\nValidity": "3 yrs",
        "Target Program": "BSc Data Analytics",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 23,
        "Name of the File": "Quess Corp.",
        "MOU Signing Date": 44467,
        "Term/\r\nValidity": "5yrs",
        "Target Program": "BBA BFSI, BBA FHM, BCom BPM, Retail Management",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 24,
        "Name of the File": "HDFC Life Insurance",
        "MOU Signing Date": 44522,
        "Term/\r\nValidity": "3 yrs",
        "Target Program": "BBA BFSI",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 25,
        "Name of the File": "MoU between DSEU & NID Kurukshetra",
        "MOU Signing Date": 44547,
        "Term/\r\nValidity": "3 yrs",
    },
    {
        "S.No.": 26,
        "Name of the File": "MoU with Bluestar (CoE)",
        "MOU Signing Date": 44554,
        "Term/\r\nValidity": "3yrs",
        "Target Program": "NA",
    },
    {
        "S.No.": 27,
        "Name of the File": "MoU between DSEU & HI NO DE Foundation",
        "MOU Signing Date": 44384,
        "Term/\r\nValidity": "5 yrs",
        "Target Program": "Japanesse Language",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 28,
        "Name of the File": "MoU between DSEU & James and Douglas",
        "MOU Signing Date": 44719,
        "Term/\r\nValidity": "5yrs",
        "Target Program": "Diploma in Interior Design",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 29,
        "Name of the File": "MoU between DSEU & Oneline Wellness",
        "MOU Signing Date": 44690,
        "Term/\r\nValidity": "5yrs",
        "Target Program": "Aesthetics and Beauty Therapy",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 30,
        "Name of the File": "MoU between DSEU & Sun Foundation",
        "MOU Signing Date": 44580,
        "Term/\r\nValidity": "3 yrs",
        "Target Program": "Scholarship *\r\nBA DMD, BMS (E-Commerce), Automobile Engineering, Computer Engineering, Cosmetology and Health, Electronics Engineering, Interior Design ",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 31,
        "Name of the File": "MoU between DSEU & Electronics Sector Skills Council of India",
        "MOU Signing Date": 44636,
        "Term/\r\nValidity": "3 yrs",
        "Target Program": "Electrical, Mechanical, Automobile, Computer, Electronics, BCA(Note sheet not in file)",
    },
    {
        "S.No.": 32,
        "Name of the File": "MoU between DSEU & Reliance Brands Ltd.",
        "MOU Signing Date": 44404,
        "Term/\r\nValidity": "3yrs",
        "Target Program": "BBA Retail Management",
        "Jurisdiction": "Mumbai",
    },
    {
        "S.No.": 33,
        "Name of the File": "MoU between DSEU & Infiniti Retail (Croma)",
        "MOU Signing Date": 44417,
        "Term/\r\nValidity": "3yrs",
        "Target Program": "BBA Retail Management",
        "Jurisdiction": "Mumbai",
    },
    {
        "S.No.": 34,
        "Name of the File": "MoU between DSEU & I-Dream Career",
        "MOU Signing Date": 44421,
        "Term/\r\nValidity": "5yrs",
        "Target Program": "BBA BFSI, BCom BPM",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 35,
        "Name of the File": "MoU between DSEU & Tech Mahindra Foundation",
        "MOU Signing Date": 44409,
        "Term/\r\nValidity": "3 Years",
        "Target Program": "Communication & Soft Sklls"
    },
    {
        "S.No.": 36,
        "Name of the File": "MoU between DSEU & CILT",
        "MOU Signing Date": 44651,
        "Term/\r\nValidity": "5 Years",
        "Target Program": "Logistics & e-commerce",
        "Jurisdiction": "Delhi"
    },
    {
        "S.No.": 37,
        "Name of the File": "MoU between DSEU & Mother Dairy fruits and vegetable Pvt. Ltd.",
        "MOU Signing Date": 44441,
        "Term/\r\nValidity": "11 Month",
        "Target Program": "Student Facility",
        "Jurisdiction": "Delhi"
    },
    {
        "S.No.": 38,
        "Name of the File": "MoU between DSEU & Thompson Press",
        "MOU Signing Date": 44531,
        "Term/\r\nValidity": "5 Year",
        "Target Program": "Printing Technology",
    },
    {
        "S.No.": 39,
        "Name of the File": "MoU between DSEU & Thyrocare",
        "MOU Signing Date": 44483,
        "Term/\r\nValidity": "3 Years",
        "Target Program": "Medical Lab Science"
    },
    {
        "S.No.": 40,
        "Name of the File": "MoU between DSEU & SRL",
        "MOU Signing Date": 44385,
        "Term/\r\nValidity": "5 years",
        "Target Program": "Medical Lab Science"
    },
    {
        "S.No.": 41,
        "Name of the File": "MoU between DSEU & NIELIT",
        "MOU Signing Date": 44802,
        "Target Program": "Content Development, Training, Exchange of Information, Joint Seminars/Conference etc"
    },
    {
        "S.No.": 42,
        "Name of the File": "Partnership between DSEU & Master G and Daughters",
        "MOU Signing Date": 44763,
        "Term/\r\nValidity": "5 Years",
        "Target Program": "BBA, BFD"
    },
    {
        "S.No.": 43,
        "Name of the File": "MoU between DSEU & Cognizant",
        "MOU Signing Date": 44452,
        "Term/\r\nValidity": "2Year",
        "Target Program": "Digital Media and Design Course",
    },
    {
        "S.No.": 44,
        "Name of the File": "MoU between DSEU & TATA Power-DDL",
        "MOU Signing Date": 44776,
        "Term/\r\nValidity": "5 Years",
        "Target Program": "Electrical Engineering\r\nIndustraial training /industry Institute interaction & All the Trades"
    },
    {
        "S.No.": 45,
        "Name of the File": "MoU between DSEU & Schneider & Kotak Mahindra Bank Ltd.",
        "MOU Signing Date": 44629,
        "Term/\r\nValidity": "4 Years\r\n01.01.2022 to 31.12.2025",
        "Target Program": "Electrical  "
    },
    {
        "S.No.": 46,
        "Name of the File": "MoU between DSEU & Mercedes Benz India Pvt. Ltd.",
        "MOU Signing Date": 44400,
        "Term/\r\nValidity": "3 Years",
        "Target Program": "ADAM"
    },
    {
        "S.No.": 47,
        "Name of the File": "MoU between DSEU & Erisha Agritech",
        "MOU Signing Date": 44741,
        "Term/\r\nValidity": "5 Year",
        "Target Program": "Automobile & Mechanical Scholarship\r\nUnder Graduate Programme",
    },
    {
        "S.No.": 48,
        "Name of the File": "MoU between DSEU & Darsh Aerospace",
        "MOU Signing Date": 44741,
        "Term/\r\nValidity": "5 year",
        "Target Program": "Automobile Engineering",
    },
    {
        "S.No.": 49,
        "Name of the File": "MoU between DSEU & Erisha E-mobility",
        "MOU Signing Date": 44741,
        "Term/\r\nValidity": "5 Year",
        "Target Program": "Scholarship & Placement\r\nAutomobile & Mechanical\r\nUnder Graduate Programme",
    },
    {
        "S.No.": 50,
        "Name of the File": "MoU between DSEU & Fincart",
        "MOU Signing Date": 44727,
        "Term/\r\nValidity": "5Year",
        "Target Program": "Scholarship stipend & Placement",
    },
    {
        "S.No.": 51,
        "Name of the File": "MoU between DSEU & Paints & Coatings Skill Council",
        "MOU Signing Date": 44748
    },
    {
        "S.No.": 52,
        "Name of the File": "MoU between DSEU & Mansycom Consultants Private Limited",
        "MOU Signing Date": 44772,
        "Term/\r\nValidity": "5Year",
        "Target Program": "Civil Engineering",
    },
    {
        "S.No.": 53,
        "Name of the File": "MoU between DSEU & Even Cargo",
        "MOU Signing Date": 44637,
        "Term/\r\nValidity": "5Year",
    },
    {
        "S.No.": 54,
        "Name of the File": "MoU between DSEU & Metropolis",
        "MOU Signing Date": 44490
    },
    {
        "S.No.": 55,
        "Name of the File": "MoU between DSEU & Academy for Computer Training (ACT) for Short term (Eng) Courses",
        "MOU Signing Date": "26.MAY.2022",
        "Term/\r\nValidity": "6 Month",
        "Target Program": "Spoken English"
    },
    {
        "S.No.": 56,
        "Name of the File": "MoU between DSEU & Macmillan for Short term (Eng) Courses",
        "MOU Signing Date": 44707,
        "Term/\r\nValidity": "12 Months",
        "Target Program": "Spoken English"
    },
    {
        "S.No.": 57,
        "Name of the File": "MoU between DSEU & Cambridge for Short term (Eng) Courses",
        "MOU Signing Date": 44707,
        "Term/\r\nValidity": "12 Month",
        "Target Program": "Spoken English"
    },
    {
        "S.No.": 58,
        "Name of the File": "MoU between DSEU & BIBA & RASCI",
        "MOU Signing Date": 44412
    },
    {
        "S.No.": 59,
        "Name of the File": "MoU between DSEU & ABFRL & RASCI",
        "MOU Signing Date": 44593
    },
    {
        "S.No.": 60,
        "Name of the File": "Partnership between DSEU & Global Alliance for Mass Entrepreneurship",
        "MOU Signing Date": 44678,
        "Term/\r\nValidity": "3 Years",
        "Target Program": "Entreprenuership"
    },
    {
        "S.No.": 61,
        "Name of the File": "MoU between DSEU & QAGENIC Technologies Pvt. Ltd.",
        "MOU Signing Date": 44826,
        "Term/\r\nValidity": "5 Years",
        "Target Program": "B.Sc.data analytics,BCA,MCA & M.Tech"
    },
    {
        "S.No.": 62,
        "Name of the File": "MoU between DSEU & CBRE South Asia Private Limited",
        "MOU Signing Date": 44838,
        "Term/\r\nValidity": "3 Year",
        "Target Program": "Building Research - Civil, Architecture\r\nFacility Mangement, Project Management & real Estate Consultancy Services",
    },
    {
        "S.No.": 63,
        "Name of the File": "MoU between DSEU & National Dong Hwa University, Taiwan",
        "MOU Signing Date": 44844,
        "Term/\r\nValidity": "Mutually Agreed to extend the afgreement to be reviewed periodically by both parties.",
        "Target Program": "BFSI \r\nFinancial and Insurane",
    },
    {
        "S.No.": 64,
        "Name of the File": "MoU between DSEU & Green Genome Pvt. Ltd.",
        "MOU Signing Date": 44881,
        "Term/\r\nValidity": "By giving at least three months prior written notice",
        "Target Program": "Agriculture development, Farm Enterprise development, value chain mangement, etc"
    },
    {
        "S.No.": 65,
        "Name of the File": "MoU between DSEU & Truecaller",
        "MOU Signing Date": 44890,
        "Term/\r\nValidity": "3 Year",
        "Target Program": "Cyber Safety and entrepreneurial skill "
    },
    {
        "S.No.": 66,
        "Name of the File": "MoU between DSEU & Altz Technologies Pvt. Ltd.",
        "MOU Signing Date": 44907,
        "Term/\r\nValidity": "3 Years / 11 Dec 2025",
        "Target Program": "B. Tech, BCA, MCA  and Diploma (Computer Engineering)"
    },
    {
        "S.No.": 67,
        "Name of the File": "Agreement between DSEU & YARS Enterprises Pvt. Ltd.",
        "MOU Signing Date": 44914,
        "Term/\r\nValidity": "3 years",
        "Target Program": "Artificial Intelligence, Machine and Deep Learning, IoT, Blockchain etc",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 68,
        "Name of the File": "MoU between DSEU and 9 Growers India Private Limited",
        "MOU Signing Date": 44907,
        "Term/\r\nValidity": "5 Year",
        "Target Program": "Under Graduate Programe to train students in Controlled Environment Agriculture (CEA)",
    },
    {
        "S.No.": 69,
        "Name of the File": "MoU between DSEU and International Business Machines (IBM)",
        "MOU Signing Date": 44851,
        "Term/\r\nValidity": "2 Year",
        "Target Program": "Computer Science &\r\nDesign Thinking",
    },
    {
        "S.No.": 70,
        "Name of the File": "MoU Between DSEU And Rotary Delhiites foundation",
        "MOU Signing Date": 45016
    },
    {
        "S.No.": 71,
        "Name of the File": "MoU Between DSEU & NBM Media Pvt. Ltd.",
        "MOU Signing Date": 44855,
        "Term/\r\nValidity": "5 Years",
        "Target Program": "Architecture, Interior Design & Mechanical Engineering"
    },
    {
        "S.No.": 72,
        "Name of the File": "MoU Between DSEU and Jakson welfare trust of Jakson Group",
        "MOU Signing Date": 44998
    },
    {
        "S.No.": 73,
        "Name of the File": "MoU between DSEU & De Box Global IT solution Pvt.Ltd.",
        "MOU Signing Date": 45043,
        "Term/\r\nValidity": "5 years",
        "Target Program": "ERP Development"
    },
    {
        "S.No.": 74,
        "Name of the File": "MoU between DSEU & Bank of Baroda",
        "MOU Signing Date": 45048,
        "Term/\r\nValidity": "5 Years",
        "Target Program": "Content Development & Staff Development"
    },
    {
        "S.No.": 75,
        "Name of the File": "MOU between DSEU and Firstsource Solution Limited",
        "MOU Signing Date": "16.01.2023",
        "Term/\r\nValidity": "5 Year",
        "Target Program": "Business Process Management",
    },
    {
        "S.No.": 76,
        "Name of the File": "Partnership between DSEU and Space 2 Grow",
        "MOU Signing Date": "25/04/2022",
        "Term/\r\nValidity": "1 Years"
    },
    {
        "S.No.": 77,
        "Name of the File": "MOU B/W DSEU & ELECTRONICS SECTOY SKILLS CEUNCIL OF iNDIA (essci)",
        "MOU Signing Date": "16.03.2022",
        "Term/\r\nValidity": "3 Year",
        "Target Program": "Electronic Sector",
    },
    {
        "S.No.": 78,
        "Name of the File": "MOU between DSEU & One Line Wellness",
        "MOU Signing Date": "09.05.22",
        "Term/\r\nValidity": "5 years",
        "Target Program": "Beauty & Aesthetic  Therapry"
    },
    {
        "S.No.": 79,
        "Name of the File": "MoU b/w DSEU & BLUE STAR (HVAC)",
        "MOU Signing Date": "06.03.2024",
        "Term/\r\nValidity": "3 years",
        "Jurisdiction": "Delhi"
    },
    {
        "S.No.": 80,
        "Name of the File": "MOU b/w DSEU & Department of Delhi Prisons govt of delhi",
        "MOU Signing Date": "26.may.2022",
        "Jurisdiction": "Delhi"
    },
    {
        "S.No.": 82,
        "Name of the File": "MoU b/w DSEU, RASCI & Tata Starbucks",
        "MOU Signing Date": 44557,
        "Term/\r\nValidity": "3 Years",
        "Target Program": "BBA Retail Management",
        "Jurisdiction": "Delhi"
    },
    {
        "S.No.": 83,
        "Name of the File": "MoU b/w DSEU & Hyundai Motors India Limited",
        "MOU Signing Date": 44172,
        "Term/\r\nValidity": "4 Years",
        "Target Program": "Automobile",
        "Jurisdiction": "Delhi"
    },
    {
        "S.No.": 84,
        "Name of the File": "MoU between DSEU & Lighthouse Communities Foundation (LCF)",
        "MOU Signing Date": 44362,
        "Term/\r\nValidity": "5 Years",
        "Target Program": "Skilling and Sustainable livelihood for youth from low income communities, create an ecosystem for skills education ..",
        "Jurisdiction": "Delhi"
    },
    {
        "S.No.": 85,
        "Name of the File": "MoU between DSEU & DWCD (Deptt. of women and child development)",
        "MOU Signing Date": 44669,
        "Term/\r\nValidity": "3 Years",
        "Target Program": "Women Entrepreneurship Program under project Samridhi through the SSK Aanganwadi hubs",
        "Jurisdiction": "Delhi"
    },
    {
        "S.No.": 86,
        "Name of the File": "MoU between DSEU & Sewan Foods Pvt. Ltd.",
        "MOU Signing Date": 44518,
        "Term/\r\nValidity": "11 Months (extendable by another 4 terms of 11 months each)",
        "Target Program": "Student Facility",
        "Jurisdiction": "Delhi",
    },
    {
        "S.No.": 87,
        "Name of the File": "Blue Star Limited",
        "MOU Signing Date": "06.03.2024"
    },
    {
        "S.No.": 88,
        "Name of the File": "Regional Institute of Education NCERT, Bhubaneswar",
        "MOU Signing Date": "05.08.2024"
    },
    {
        "S.No.": 89,
        "Name of the File": "Johnson Controls-Hitachi Air Conditioning India Limited",
        "MOU Signing Date": "18.10.2024"
    },
    {
        "S.No.": 90,
        "Name of the File": "Jakson Welfare Trust",
        "MOU Signing Date": "23.10.2024"
    },
    {
        "S.No.": 91,
        "Name of the File": "Entrepreneurship Development Institute of India (EDII) Ahmedabad, Gujarat",
        "MOU Signing Date": "12.11.2024"
    },
    {
        "S.No.": 92,
        "Name of the File": "Tech Mahindra Foundation ",
        "MOU Signing Date": "13.12.2024"
    }
]