const jobPortalTabs = [
    {
        id: "academic positions",
        label: "Academic Positions",
        empty: "No academic positions found.",
    },
    {
        id: "non academic positions",
        label: "Non Academic Positions",
        empty: "No non-academic positions found.",
    },
    {
        id: "short term positions",
        label: "Short-Term Positions",
        empty: "No short-term positions found.",
    },
    {
        id: "results",
        label: "Results",
        empty: "No results found.",
    },
    {
        id: "recruitments and notice",
        label: "Notice",
        empty: "No recruitments or notices found.",
    },
];


export { jobPortalTabs };
