import News1 from '../assets/News/News1.jpg';
import Event1 from '../assets/News/Event1.jpg';
import News3 from '../assets/News/News3.jpg';
import News4 from '../assets/News/News4.jpg';
import News5 from '../assets/News/News5.jpg';
import News6 from '../assets/News/News6.jpg';
import News7 from '../assets/News/News7.jpg';

export const newsItems = [
    {
        id: 3,
        image: News4,
        title: 'Research Excellence Award',
        description: 'University recognized for outstanding research achievements',
        link: '/news/research-award',
    },
    {
        id: 4,
        image: News5,
        title: 'Student Startup Success',
        description: 'Students launch a successful AI-based startup',
        link: '/news/student-startup',
    },
    {
        id: 6,
        image: News6,
        title: 'Cultural Fest Highlights',
        description: 'A week full of creativity, performances, and celebration',
        link: '/news/cultural-fest',
    },
    {
        id: 7,
        image: News7,
        title: 'Alumni Meet 2025',
        description: 'Reconnecting with our alumni community and celebrating milestones',
        link: '/news/alumni-meet',
    },
    {
        id: 5,
        image: Event1,
        title: "Event1",
        description: "event 1 description",
        link: '/news/event1'
    },
    {
        id: 1,
        image: News1,
        title: 'Campus Innovation Hub Launch',
        description: 'New innovation hub to foster entrepreneurship',
        link: '/news/innovation-hub',
    },
    {
        id: 2,
        image: News3,
        title: 'Industry Partnership',
        description: 'Collaboration with leading tech companies',
        link: '/news/partnership',
    },
];
