import News1 from '../assets/News/News1.jpg';
import News3 from '../assets/News/News3.jpg';
import News4 from '../assets/News/News4.jpg';
import Event1 from '../assets/News/Event1.jpg';
import Event2 from '../assets/News/Event2.jpg';

export const newsItems = [
    {
        id: 5,
        image: Event1,
        title: "Event1",
        description: "event 1 description",
        link: '/news/event1'
    },
    {
        id: 6,
        image: Event2,
        title: "Event2",
        description: "event 2 description",
        link: '/news/Event2'
    },
    {
        id: 1,
        image: News1,
        title: 'Campus Innovation Hub Launch',
        description: 'New innovation hub to foster entrepreneurship',
        link: '/news/innovation-hub',
    },
    {
        id: 2,
        image: News3,
        title: 'Industry Partnership',
        description: 'Collaboration with leading tech companies',
        link: '/news/partnership',
    },
    {
        id: 3,
        image: News1,
        title: 'Student Achievement',
        description: 'National robotics competition winners',
        link: '/news/achievement',
    },
    {
        id: 4,
        image: News4,
        title: 'Community Outreach',
        description: 'Skill development workshop success',
        link: '/news/outreach',
    },
];