export const REGISTRARINFO = {
  name: "Prof. (Dr.) Gagan Dhawan",
  designation: "Registrar",
  university: "Delhi Skill and Entrepreneurship University (DSEU)",

  profileOverview: `
    Prof. (Dr.) Gagan Dhawan completed his graduation and post-graduation at the <b>University of Delhi, India</b>. 
    He received the <i>Universitas 21 Fellowship</i> for a <b>Master’s in Bioinformatics</b> at the University of Edinburgh, UK, 
    and the <i>UGC-Raman Award</i> for postdoctoral research at the University of Massachusetts, Boston, USA. 
    He is a Fellow of the Royal Society of Chemistry (FRSC), UK, and a <i>Chartered Chemist (CChem)</i>. 
    Recognized for his excellence in teaching, he received the <i>Meritorious Teacher Award (2014)</i> and <b>INSA Teachers Award (2020)</b>. 
    He currently serves as a Council Member at the National Commission for Allied and Healthcare Professions (NCAHP), 
    under the Ministry of Health and Family Welfare, Government of India. 
    His research focuses on developing <i>novel small-molecule inhibitors</i> and <b>natural polymer-based self-assembled nanostructures</b> 
    for biomedical applications.
  `,

  message:
    "Education is more than knowledge; it's the ability to create change. DSEU empowers learners with the skills, confidence, and mindset to tackle challenges and shape a better society.",
};
