import activity1 from "/src/assets/Activities/Activities1.jpg";
import activity2 from "/src/assets/Activities/Activities2.jpg";
import activity3 from "/src/assets/Activities/Activities3.jpg";
import activity4 from "/src/assets/Activities/Activities4.jpg";
import activity5 from "/src/assets/Activities/Activities5.jpg";
import activity6 from "/src/assets/Activities/Activities6.jpg";
import activity7 from "/src/assets/Activities/Activities7.jpeg";
// import activity9 from "/src/assets/Activities/Activities9.jpg";
import activity10 from "/src/assets/Activities/Activities10.jpg";
import activity11 from "/src/assets/Activities/Activities11.jpg";
// import activity14 from "/src/assets/Activities/Activities14.jpg";
// import activity15 from "/src/assets/Activities/Activities15.jpg";
// import activity16 from "/src/assets/Activities/Activities16.jpg";  
import activity18 from "/src/assets/Activities/Activities18.jpg";
import activity19 from "../assets/Activities/Activities19.jpg";

import thumbnail1 from "/src/assets/thumbnail/thumbnail1.jpg";
import thumbnail3 from "/src/assets/thumbnail/thumbnail3.jpg";
import thumbnail4 from "/src/assets/thumbnail/thumbnail4.jpg";
import thumbnail5 from "/src/assets/thumbnail/thumbnail5.jpg";
import thumbnail6 from "/src/assets/thumbnail/thumbnail6.jpg";

import admissionthumb from '../assets/thumbnail/admission.png';

export const allImages = [
  activity1,
  activity2,
  activity3,
  activity4,
  activity5,
  activity6,
  activity7,
  activity10,
  activity11,
  activity18,
  activity19,
];


export const priorityVideo = {
  thumbnail: admissionthumb,
  title: "DSEU Admission form filling steps",
  subheading: "",
  link: "https://youtu.be/MB3TbJOf0S4",
};

export const videoData = [
  {
    thumbnail: thumbnail1,
    title: "Valedictory Speech of Hon'ble Vice Chancellor, DSEU",
    subheading: "",
    link: "https://www.youtube.com/watch?v=RV42xYACFZM&t=320s",
  },
  {
    thumbnail: thumbnail3,
    title: "DSEU Chetak Awards",
    subheading: "",
    link: "https://www.youtube.com/watch?v=RfnC6ltc9pg",
  },
  {
    thumbnail: thumbnail4,
    title: "G20 Fashionista organised at DSEU",
    subheading: "",
    link: "https://www.youtube.com/watch?v=_2nZ5XGAzgg",
  },
  {
    thumbnail: thumbnail5,
    title: "DSEU Talks on Women's Welfare to Women Led Development",
    subheading: "",
    link: "https://www.youtube.com/watch?v=pXfQx0dD8R0&ab_channel=DSEUTalks",
  },
  {
    thumbnail: thumbnail6,
    title: "Motivational Talk for Faculty and Students",
    subheading: "",
    link: "https://www.youtube.com/watch?v=Zwguntx_v68&ab_channel=DSEUTalks",
  },
];